# This is a developement only file, production has a seperate docker compose which is not visible on github
version: "3.8"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
  
  backend:
    build:
      context: ./backend
    image: backend
    container_name: backend
    expose:
      - 6060
    volumes:
      - ./backend/secrets.json:/secrets.json
    restart: unless-stopped
    networks:
      - docker

networks:
  docker: